grupa_152 = [{'Nr. Crt.': 1, 'Nr. Matricol': '241/2021', 'Adresa institutionala': 'andrei-cristian.airinei@s.unibuc.ro',
              'Numele si prenumele': 'Airinei C Andrei-Cristian', 'Grupa': 152},
             {'Nr. Crt.': 2, 'Nr. Matricol': '278/2021', 'Adresa institutionala': 'victor-stefan.badulescu@s.unibuc.ro',
              'Numele si prenumele': 'Bădulescu  CP Victor-Ștefan', 'Grupa': 152},
             {'Nr. Crt.': 3, 'Nr. Matricol': '271/2021',
              'Adresa institutionala': 'albert-ionut.balauta-amargheoalei@s.unibuc.ro',
              'Numele si prenumele': 'Bălăuță-Amargheoalei L.A. Albert-Ionuț', 'Grupa': 152},
             {'Nr. Crt.': 4, 'Nr. Matricol': '270/2021', 'Adresa institutionala': 'alexandru-ioan.banilean@s.unibuc.ro',
              'Numele si prenumele': 'Bănilean V. Alexandru-Ioan', 'Grupa': 152},
             {'Nr. Crt.': 5, 'Nr. Matricol': '234/2021', 'Adresa institutionala': 'daniel-stefan.boni@s.unibuc.ro',
              'Numele si prenumele': 'Boni I Daniel-Stefan', 'Grupa': 152}, {'Nr. Crt.': 6, 'Nr. Matricol': '298/2021',
                                                                             'Adresa institutionala': 'eduard-robert.brasoveanu@s.unibuc.ro',
                                                                             'Numele si prenumele': 'Brașoveanu C.A. Eduard-Robert-Paul',
                                                                             'Grupa': 152},
             {'Nr. Crt.': 7, 'Nr. Matricol': '300/2021', 'Adresa institutionala': 'tudor-nicolae.cioc@s.unibuc.ro',
              'Numele si prenumele': 'Cioc I Tudor-Nicolae', 'Grupa': 152},
             {'Nr. Crt.': 8, 'Nr. Matricol': '307/2021', 'Adresa institutionala': 'maria-simona.cioclov@s.unibuc.ro',
              'Numele si prenumele': 'Cioclov I Maria-Simona', 'Grupa': 152},
             {'Nr. Crt.': 9, 'Nr. Matricol': '306/2021', 'Adresa institutionala': 'cristina.damov@s.unibuc.ro',
              'Numele si prenumele': 'Damov S Cristina', 'Grupa': 152}, {'Nr. Crt.': 10, 'Nr. Matricol': '245/2021',
                                                                         'Adresa institutionala': 'teodora-cosmina.diaconescu@s.unibuc.ro',
                                                                         'Numele si prenumele': 'Diaconescu L Teodora Cosmina',
                                                                         'Grupa': 152},
             {'Nr. Crt.': 11, 'Nr. Matricol': '244/2021', 'Adresa institutionala': 'andrei-dragos.dimitriu@s.unibuc.ro',
              'Numele si prenumele': 'Dimitriu V Andrei-Dragoș', 'Grupa': 152},
             {'Nr. Crt.': 12, 'Nr. Matricol': '233/2021', 'Adresa institutionala': 'mircea.donciu@s.unibuc.ro',
              'Numele si prenumele': 'Donciu DC Mircea', 'Grupa': 152}, {'Nr. Crt.': 13, 'Nr. Matricol': '268/2021',
                                                                         'Adresa institutionala': 'tudor-constantin.dumitrescu@s.unibuc.ro',
                                                                         'Numele si prenumele': 'Dumitrescu D Tudor-Constantin',
                                                                         'Grupa': 152},
             {'Nr. Crt.': 14, 'Nr. Matricol': '275/2021',
              'Adresa institutionala': 'razvan-cristian.dumitriu@s.unibuc.ro',
              'Numele si prenumele': 'Dumitriu A.C.T. Răzvan-Cristian', 'Grupa': 152},
             {'Nr. Crt.': 15, 'Nr. Matricol': '250/2021', 'Adresa institutionala': 'liviu-armand.gheorghe@s.unibuc.ro',
              'Numele si prenumele': 'Gheorghe V Liviu Armand', 'Grupa': 152},
             {'Nr. Crt.': 16, 'Nr. Matricol': '265/2021', 'Adresa institutionala': 'tudor.haulica@s.unibuc.ro',
              'Numele si prenumele': 'Hăulică M.D. Tudor', 'Grupa': 152},
             {'Nr. Crt.': 17, 'Nr. Matricol': '365/2021', 'Adresa institutionala': 'mihail-costin.mantopol@s.unibuc.ro',
              'Numele si prenumele': 'Mantopol MC Mihail-Costin', 'Grupa': 152},
             {'Nr. Crt.': 18, 'Nr. Matricol': '253/2021', 'Adresa institutionala': 'stefan.moldoveanu@s.unibuc.ro',
              'Numele si prenumele': 'Moldoveanu C Ștefan', 'Grupa': 152},
             {'Nr. Crt.': 19, 'Nr. Matricol': '248/2021', 'Adresa institutionala': 'eric-alexandru.morosan@s.unibuc.ro',
              'Numele si prenumele': 'Moroșan F Eric-Alexandru', 'Grupa': 152},
             {'Nr. Crt.': 20, 'Nr. Matricol': '267/2021', 'Adresa institutionala': 'andrei-cristian.murica@s.unibuc.ro',
              'Numele si prenumele': 'Murică C Andrei-Cristian', 'Grupa': 152},
             {'Nr. Crt.': 21, 'Nr. Matricol': '277/2021', 'Adresa institutionala': 'radu-ioan.nedelcu@s.unibuc.ro',
              'Numele si prenumele': 'Nedelcu S Radu-Ioan', 'Grupa': 152},
             {'Nr. Crt.': 22, 'Nr. Matricol': '260/2021', 'Adresa institutionala': 'andrei-bogdan.nicula@s.unibuc.ro',
              'Numele si prenumele': 'Nicula M.R. Andrei-Bogdan', 'Grupa': 152},
             {'Nr. Crt.': 23, 'Nr. Matricol': '236/2021', 'Adresa institutionala': 'mihai-adrian.oprea@s.unibuc.ro',
              'Numele si prenumele': 'Oprea G Mihai-Adrian', 'Grupa': 152},
             {'Nr. Crt.': 24, 'Nr. Matricol': '247/2021', 'Adresa institutionala': 'ionut-alexandru.pascu@s.unibuc.ro',
              'Numele si prenumele': 'Pascu M.C. Ionuț-Alexandru', 'Grupa': 152},
             {'Nr. Crt.': 25, 'Nr. Matricol': '299/2021',
              'Adresa institutionala': 'marius-cristian.petrica@s.unibuc.ro',
              'Numele si prenumele': 'Petrică F Marius-Cristian', 'Grupa': 152},
             {'Nr. Crt.': 26, 'Nr. Matricol': '255/2021', 'Adresa institutionala': 'catalin-andrei.stan@s.unibuc.ro',
              'Numele si prenumele': 'Stan N. Cătălin-Andrei', 'Grupa': 152},
             {'Nr. Crt.': 27, 'Nr. Matricol': '239/2021', 'Adresa institutionala': 'robert-gabriel.trifan@s.unibuc.ro',
              'Numele si prenumele': 'Trifan S Robert-Gabriel', 'Grupa': 152},
             {'Nr. Crt.': 28, 'Nr. Matricol': '256/2021', 'Adresa institutionala': 'alexandru.visan@s.unibuc.ro',
              'Numele si prenumele': 'Visan G Alexandru', 'Grupa': 152},
             {'Nr. Crt.': 29, 'Nr. Matricol': '280/2021', 'Adresa institutionala': 'stefan.voicu1@s.unibuc.ro',
              'Numele si prenumele': 'VOICU PI STEFAN', 'Grupa': 152},
             {'Nr. Crt.': 30, 'Nr. Matricol': '290/2021', 'Adresa institutionala': 'ion-catalin.zdircea@s.unibuc.ro',
              'Numele si prenumele': 'Zdîrcea I Ion-Cătălin', 'Grupa': 152}]

grupa_143 = [{'Nr. Crt.': 31, 'Nr. Matricol': None, 'Adresa institutionala': 'alexaxyz12@gmail.com',
              'Numele si prenumele': 'Lung Alexandra', 'Grupa': None},
             {'Nr. Crt.': 32, 'Nr. Matricol': None, 'Adresa institutionala': 'alex.gabriel340@gmail.com',
              'Numele si prenumele': 'Totolici Alexandru', 'Grupa': None},
             {'Nr. Crt.': 33, 'Nr. Matricol': None, 'Adresa institutionala': 'allealexandra1313@gmail.com',
              'Numele si prenumele': 'Paun Andreea Alexandra', 'Grupa': None},
             {'Nr. Crt.': 34, 'Nr. Matricol': None, 'Adresa institutionala': 'bby.mbriana@yahoo.com',
              'Numele si prenumele': 'M. Briana', 'Grupa': None},
             {'Nr. Crt.': 35, 'Nr. Matricol': None, 'Adresa institutionala': 'crivoicarla02@gmail.com',
              'Numele si prenumele': 'Crivoi Carla', 'Grupa': None},
             {'Nr. Crt.': 36, 'Nr. Matricol': None, 'Adresa institutionala': 'cazacucristiangabriel13@gmail.com',
              'Numele si prenumele': 'Cazacu Cristian-Gabriel', 'Grupa': None},
             {'Nr. Crt.': 37, 'Nr. Matricol': None, 'Adresa institutionala': 'diliricimihai@gmail.com',
              'Numele si prenumele': 'Mihai Dilirici', 'Grupa': None},
             {'Nr. Crt.': 38, 'Nr. Matricol': None, 'Adresa institutionala': 'franci.pasare@gmail.com',
              'Numele si prenumele': 'Pasăre Francisca', 'Grupa': None},
             {'Nr. Crt.': 39, 'Nr. Matricol': None, 'Adresa institutionala': 'ilincanechita237@gmail.com',
              'Numele si prenumele': 'Nechita Ilinca', 'Grupa': None},
             {'Nr. Crt.': 40, 'Nr. Matricol': None, 'Adresa institutionala': 'ghetoiu.laurentiu@gmail.com',
              'Numele si prenumele': 'Ghetoiu Laurentiu', 'Grupa': None},
             {'Nr. Crt.': 41, 'Nr. Matricol': None, 'Adresa institutionala': 'Marianita162460@gmail.com',
              'Numele si prenumele': 'Cucoș Marianita', 'Grupa': None},
             {'Nr. Crt.': 42, 'Nr. Matricol': None, 'Adresa institutionala': 'marinee.anca2002@gmail.com',
              'Numele si prenumele': 'Chiricuta Marina', 'Grupa': None},
             {'Nr. Crt.': 43, 'Nr. Matricol': None, 'Adresa institutionala': 'hutanmihai29@gmail.com',
              'Numele si prenumele': 'Hutan Mihai', 'Grupa': None},
             {'Nr. Crt.': 44, 'Nr. Matricol': None, 'Adresa institutionala': 'mihaimilitaru30@yahoo.com',
              'Numele si prenumele': 'Militaru Mihai', 'Grupa': None},
             {'Nr. Crt.': 45, 'Nr. Matricol': None, 'Adresa institutionala': 'madalinflorea1907@gmail.com',
              'Numele si prenumele': 'Florea Mădălin', 'Grupa': None},
             {'Nr. Crt.': 46, 'Nr. Matricol': None, 'Adresa institutionala': 'nabil.alhfz98@gmail.com',
              'Numele si prenumele': 'Alhafez Nabil', 'Grupa': None},
             {'Nr. Crt.': 47, 'Nr. Matricol': None, 'Adresa institutionala': 'pauldumitru20@gmail.com',
              'Numele si prenumele': 'Dumitru Paul', 'Grupa': None},
             {'Nr. Crt.': 48, 'Nr. Matricol': None, 'Adresa institutionala': 'petru.theodor.cristea@gmail.com',
              'Numele si prenumele': 'Cristea Petru-Theodor', 'Grupa': None},
             {'Nr. Crt.': 49, 'Nr. Matricol': None, 'Adresa institutionala': 'radu.besliu02@gmail.com',
              'Numele si prenumele': 'Besliu Radu', 'Grupa': None},
             {'Nr. Crt.': 50, 'Nr. Matricol': None, 'Adresa institutionala': 'robertmessi2002@gmail.com',
              'Numele si prenumele': 'Gheorghe Robert', 'Grupa': None},
             {'Nr. Crt.': 51, 'Nr. Matricol': None, 'Adresa institutionala': 'florinpetrisortanasa02@gmail.com',
              'Numele si prenumele': 'Florin Petrisor Tanasa', 'Grupa': None},
             {'Nr. Crt.': 52, 'Nr. Matricol': None, 'Adresa institutionala': 'vali2wd@gmail.com',
              'Numele si prenumele': 'Nafornita Valentin', 'Grupa': None},
             {'Nr. Crt.': 53, 'Nr. Matricol': None, 'Adresa institutionala': 'petrevasileeduard@gmail.com',
              'Numele si prenumele': 'Petre Vasile-Eduard', 'Grupa': None},
             {'Nr. Crt.': 54, 'Nr. Matricol': None, 'Adresa institutionala': 'niculitacristiana@gmail.com',
              'Numele si prenumele': 'cristiana ¡', 'Grupa': None}]
